# Configuration fields for RICC
case: _Test4
graph: Enron
edge_manipulation_cost: equal
target_node_type: close
attack: NNI
epoch: 3000
lr: 0.005
buffer: 0.8
sampling_size: 100
interval: 15
num_modified_edges: 70
num_added_nodes: 110
num_target_nodes: 100

# Configuration fields for collective classification
theta: 0.5
weight: 0.01
iteration: 6
threshold: 0
